spring.application.name=lawfirm-api

server.forward-headers-strategy=framework
server.port=${PORT:8080}

# ===============================
# DATABASE (Railway + fallback Docker)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# MINIO (disable for Railway)
# ===============================
# minio.url=http://minio:9000
# minio.access.name=admin
# minio.access.secret=Password123#
# minio.bucket.name=lawfirm-bucket

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.resolve-schema-properties=true

# ===============================
# EMAIL (use ENV)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB

# ===============================
# HIKARI (optional)
# ===============================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.defer-datasource-initialization=true