spring.application.name=lawfirm-api
#server.address=0.0.0.0
server.forward-headers-strategy=framework
#setup postgres db
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/lawfirm_db
#spring.datasource.username=postgres
#spring.datasource.password=123
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lawfirm_db
spring.datasource.username=postgres
spring.datasource.password=123
springdoc.api-docs.resolve-schema-properties=true
#spring.jpa.open-in-view=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#minio port
minio.url=http://localhost:9000
minio.access.name=admin
minio.access.secret=@Password123!
minio.bucket.name=lawfirm-bucket

# Config Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=gclawgroup168@gmail.com
spring.mail.password=lrkm gmig jyvl dbfz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB