spring.application.name=lawfirm-api

server.forward-headers-strategy=framework
server.port=8080

# ===============================
# DATABASE (Docker)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/lawfirm_db
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# MINIO (Docker)
# ===============================
minio.url=http://minio:9000
minio.access.name=admin
minio.access.secret=Password123#
minio.bucket.name=lawfirm-bucket

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.resolve-schema-properties=true

# ===============================
# EMAIL CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gclawgroup168@gmail.com
spring.mail.password=lrkm gmig jyvl dbfz

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.defer-datasource-initialization=true